server:
  port: 8080
  address: 127.0.0.1
spring:
  mvc:
    throw-exception-if-no-handler-found: true
    servlet:
      # undertow启动容器时不会初始化，设置为1进行初始化
      load-on-startup: 1
  application:
    name: rocketmq

rocketmq:
  name-server: 192.168.1.224:9876 # 访问地址
  producer:
    group: Pro_Group # 必须指定group
    send-message-timeout: 3000 # 消息发送超时时长，默认3s
    retry-times-when-send-failed: 3 # 同步发送消息失败重试次数，默认2
    retry-times-when-send-async-failed: 3 # 异步发送消息失败重试次数，默认2
